### ISSUE TITLE
Installation issue on Ubuntu

### ISSUE THREAD

**Issue by thokra** [Mon-Ouie/ray#47]
Hi!
I'm having some issues installing Ray 0.2.0 on my Ubuntu machine. 0.1.1 works just fine, but not Ray 0.2
Terminal output:

```
Building native extensions.  This could take a while...
ERROR:  Error installing ray:
  ERROR: Failed to build gem native extension.

        /home/thomas/.rvm/rubies/ruby-1.9.2-p290/bin/ruby extconf.rb
checking for GL/glxext.h... yes
checking for X11/extensions/Xrandr.h... yes
checking for main() in -lXrandr... yes
checking for main() in -lX11... yes
checking for main() in -lGL... yes
checking for main() in -lGLEW... yes
checking for main() in -lopenal... yes
checking for main() in -lsndfile... yes
creating Makefile

make
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o say_basic_type.o -c say_basic_type.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o gl_index_buffer.o -c gl_index_buffer.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o color.o -c color.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o pixel_bus.o -c pixel_bus.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o say_thread.o -c say_thread.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o say_view.o -c say_view.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o image.o -c image.c
image.c: In function ‘ray_image_assert_pos’:
image.c:161:14: warning: format ‘%ld’ expects type ‘long int’, but argument 3 has type ‘size_t’
image.c:161:14: warning: format ‘%ld’ expects type ‘long int’, but argument 4 has type ‘size_t’
image.c:165:14: warning: format ‘%ld’ expects type ‘long int’, but argument 3 has type ‘size_t’
image.c:165:14: warning: format ‘%ld’ expects type ‘long int’, but argument 4 has type ‘size_t’
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o audio.o -c audio.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o gl_vertex.o -c gl_vertex.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o say_string.o -c say_string.c
gcc -I. -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/thomas/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -DHAVE_GL_GLXEXT_H -DHAVE_X11_EXTENSIONS_XRANDR_H  -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -Wextra -Wall -Wno-unused-parameter -std=gnu99 -I/usr/include/freetype2 -DSAY_X11  -o say_context.o -c say_context.c
say_context.c: In function ‘say_context_glew_init’:
say_context.c:231:3: error: ‘glVertexAttribDivisor’ undeclared (first use in this function)
say_context.c:231:3: note: each undeclared identifier is reported only once for each function it appears in
make: *** [say_context.o] Error 1


Gem files will remain installed in /home/thomas/.rvm/gems/ruby-1.9.2-p290@utvikling/gems/ray-0.2.0 for inspection.
Results logged to /home/thomas/.rvm/gems/ruby-1.9.2-p290@utvikling/gems/ray-0.2.0/ext/gem_make.out
```

Would appreciate any help, using 0.1.1 until then :)

Thomas

**Comment by Mon-Ouie** [comment]
I think this is related to the GLEW version you are using. I know it compiles fine with GLEW 1.6. Scaning through GLEW's changelog, this function should be in the header since 1.5.1.

**Comment by thokra** [comment]
Updating worked like a charm. Had `1.5.7.is.1.5.2-1ubuntu2` installed, but upgrading to `1.6.0-3` worked.

Added `deb http://se.archive.ubuntu.com/ubuntu/ oneiric universe` to the repositories list, and installed `libglew1.6-dev` from Synaptic Package Manager.

Thanks! :)
